package com.example.fitnesstrackerapi.repo.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

import java.io.Serializable;
import java.util.Date;
import java.util.UUID;

@Builder
@Getter
@Setter
//@AllArgsConstructor   // why dont these annotations work?
//@NoArgsConstructor
@EqualsAndHashCode
@Data
@DynamoDBTable(tableName="Workouts")
public class Workout implements Serializable {

    @DynamoDBHashKey
    //@DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String type;
    //private Date date;

    @DynamoDBAttribute
    private Double maxWeight;

    public Workout() {

    }

    public Workout(String type, Double maxWeight) {
        this.id = UUID.randomUUID().toString();
        this.type = type;
        //this.date = date;
        this.maxWeight = maxWeight;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }
/*
    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }
*/
    public Double getMaxWeight() {
        return maxWeight;
    }

    public void setMaxWeight(Double maxWeight) {
        this.maxWeight = maxWeight;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
}
